tasks:
  - Genhexapod1_genhexapod__KneeNum_l1-0_l2-0_l3-0_l4-0_l5-0_l6-0__ScaleJointLimit_l1-0_l2-0_l3-0_l4-0_l5-0_l6-0_1_0__Geo_scale_all_1_2
  - Genhexapod10_genhexapod__KneeNum_l1-0_l2-0_l3-0_l4-0_l5-0_l6-0__ScaleJointLimit_l1-0_l2-0_l3-0_l4-0_l5-0_l6-0_1_0__Geo_lengthen_calf_0_4
  - Genhexapod202_genhexapod__KneeNum_l1-2_l2-2_l3-2_l4-2_l5-2_l6-2__ScaleJointLimit_l1-1_l2-1_l3-1_l4-1_l5-1_l6-1_0_8__Geo_lengthen_thigh_1_2
  - Genhexapod203_genhexapod__KneeNum_l1-2_l2-2_l3-2_l4-2_l5-2_l6-2__ScaleJointLimit_l1-1_l2-1_l3-1_l4-1_l5-1_l6-1_0_8__Geo_lengthen_thigh_0_8
  - Gendog10_gendog__KneeNum_fl0_fr0_rl0_rr0__ScaleJointLimit_fl0_fr0_rl0_rr0_1_0__Geo_lengthen_calf_0_4
  - Gendog100_gendog__KneeNum_fl1_fr1_rl1_rr1__ScaleJointLimit_fl1_fr0_rl1_rr0_0_8__Geo_scale_all_1_2
  - Gendog200_gendog__KneeNum_fl2_fr2_rl2_rr2__ScaleJointLimit_fl1_fr0_rl1_rr0_0_8__Geo_scale_all_0_8
  - Gendog50_gendog__KneeNum_fl1_fr1_rl1_rr1__ScaleJointLimit_fl1_fr1_rl0_rr0_1_2__Geo_lengthen_thigh_0_4
  - Gendog115_gendog__KneeNum_fl2_fr2_rl2_rr2__ScaleJointLimit_fl0_fr0_rl0_rr0_1_0__Geo_lengthen_thigh_0_8
  - Genhumanoid100_genhumanoid__KneeNum_l1_r1__ScaleJointLimit_l0_r1_1_2__Geo_lengthen_calf_0_4
  - Genhumanoid10_genhumanoid__KneeNum_l0_r0__ScaleJointLimit_l0_r0_1_0__Geo_lengthen_calf_0_4
model: urma
exp_name: urma_10_100_200_50_haxa1_randomized_additive_bs512_acc2
batch_size: 512
lr: 0.0003
num_workers: 32
num_epochs: 75
gradient_acc_steps: 2
